const { chromium } = require(process.env.PLAYWRIGHT_MODULE || "playwright");
const fs = require("node:fs");
const assert = require("node:assert/strict");
const path = require("node:path");
(async () => {
 const out = process.env.LAB_EVIDENCE_DIR || require("node:path").join(require("node:os").tmpdir(), "meetmind-semantic-lab-evidence");
 fs.mkdirSync(out, { recursive: true });
 const browser = await chromium.launch({ ...(process.env.CHROMIUM_EXECUTABLE ? { executablePath: process.env.CHROMIUM_EXECUTABLE } : {}), headless: true });
 const page = await browser.newPage({ viewport: { width: 1440, height: 1060 }, deviceScaleFactor: 1 });
 const errors = [];
 page.on("pageerror", e => errors.push(e.message));
 page.on("console", m => { if(m.type() === "error") errors.push(m.text()); });
 await page.goto(process.env.LAB_URL || "http://127.0.0.1:4191/");
 await page.locator("#sequence").filter({ hasText: "事件 #8" }).waitFor();
 await page.screenshot({ path: path.join(out, "desktop-initial.png"), fullPage: true });
 await page.waitForFunction(() => JSON.parse(document.querySelector("#diagnostic").textContent).drawCalls > 10);
 const before = await page.locator("#diagnostic").textContent();
 await page.getByLabel("作品标题", { exact: true }).fill("我们一起折出的纸桥");
 await page.getByRole("button", { name: "保存纠正", exact: true }).click();
 await page.getByRole("heading", { name: "我们一起折出的纸桥", exact: true }).waitFor();
 const stateBeforeMode = await page.locator("#json").textContent();
 await page.getByLabel("呈现模式", { exact: true }).selectOption("2d");
 await page.locator(".baseline").waitFor({ state: "visible" });
 await page.locator(".viewport").waitFor({ state: "hidden" });
 if(await page.locator("#json").textContent() !== stateBeforeMode) throw new Error("Mode switch changed state");
 await page.waitForFunction(() => JSON.parse(document.querySelector("#diagnostic").textContent).mode === "2d");
 const pausedFrames = JSON.parse(await page.locator("#diagnostic").textContent()).renderedFrames;
 await page.waitForTimeout(1100);
 if(JSON.parse(await page.locator("#diagnostic").textContent()).renderedFrames !== pausedFrames) throw new Error("2D continued WebGL rendering");
 if(await page.locator(".baseline-relation").count() !== 4) throw new Error("2D missing relationships");

 const baselineCards = await page.locator(".baseline-card").count();
 if (baselineCards !== 5) throw new Error("2D baseline did not render the same visible entities");
 await page.locator(".baseline-card").filter({ hasText: "共同作品" }).click();
 await page.getByRole("heading", { name: "我们一起折出的纸桥", exact: true }).waitFor();
 await page.getByLabel("呈现模式", { exact: true }).selectOption("3d");
 await page.locator(".viewport").waitFor({ state: "visible" });
 await page.getByRole("heading", { name: "我们一起折出的纸桥", exact: true }).waitFor();
 const corrected = JSON.parse(await page.locator("#diagnostic").textContent());
 const previous = JSON.parse(before);
 if(corrected.objects.find(o=>o.id==="artifact-1").uuid !== previous.objects.find(o=>o.id==="artifact-1").uuid) throw new Error("Correction replaced 3D object");
 if(await page.locator(".stages button.active").count()) throw new Error("Custom event marked a preset stage");
 await page.locator('#entities [data-entity-id="action-1"]').click();
 await page.getByRole("button", { name: "我愿意参加", exact: true }).click();
 await page.getByLabel("现实结果说明").waitFor();
 await page.getByLabel("查看身份", { exact: true }).selectOption("bo");
 await page.getByRole("button", { name: "这次不参加", exact: true }).click();
 await page.locator(".decision").filter({ hasText: "阿博" }).filter({ hasText: "这次不参加" }).waitFor();
 await page.getByLabel("查看身份", { exact: true }).selectOption("alice");
 await page.getByLabel("现实结果说明").fill("我完成了后续创作，阿博没有参加。");
 await page.getByRole("button", { name: "自报已完成", exact: true }).click();
 await page.getByRole("button", { name: "撤回我的结果报告", exact: true }).waitFor();
 await page.screenshot({ path: path.join(out, "desktop-outcome.png"), fullPage: true });
 await page.getByRole("button", { name: "撤回我的结果报告", exact: true }).click();
 await page.getByLabel("现实结果说明").waitFor();
 await page.locator('#entities [data-entity-id="memory-1"]').click();
 await page.getByRole("button", { name: "撤回这段经历", exact: true }).click();
 await page.locator('#entities [data-entity-id="memory-1"]').waitFor({ state: "detached" });
 await page.locator('#entities [data-entity-id="action-1"]').click();
 await page.locator("#detail .warning").waitFor();
 const finalState = JSON.parse(await page.locator("#json").textContent());
 if(finalState.relationships.length !== 0) throw new Error("Dangling relationships remain");
 await page.getByLabel("查看身份", { exact: true }).selectOption("observer");
 await page.locator('#entities [data-entity-id="candidate-e"]').waitFor();
 await page.getByLabel("查看身份", { exact: true }).selectOption("alice");
 await page.locator('#entities [data-entity-id="candidate-e"]').waitFor({ state: "detached" });
 await page.getByRole("button", { name: "提出行动", exact: true }).click();
 await page.locator("#sequence").filter({ hasText: "事件 #8" }).waitFor();
 const shotBefore = await page.locator("canvas").screenshot();
 const box = await page.locator("canvas").boundingBox();
 await page.mouse.move(box.x + box.width * .3, box.y + box.height * .7);
 await page.mouse.down();
 await page.mouse.move(box.x + box.width * .65, box.y + box.height * .6, { steps: 12 });
 await page.mouse.up();
 const shotAfter = await page.locator("canvas").screenshot();
 if(shotBefore.equals(shotAfter)) throw new Error("Orbit input did not change canvas");
 await page.locator(".object-label").filter({hasText:"共同完成的纸桥"}).click();
 await page.getByRole("heading", {name:"共同完成的纸桥",exact:true}).waitFor();
 await page.locator('#entities [data-entity-id="action-1"]').click();
 await page.setViewportSize({ width: 390, height: 844 });
 await page.screenshot({ path: path.join(out, "mobile-action.png"), fullPage: true });
 await page.getByRole("button", {name:"我愿意参加",exact:true}).click();
 await page.getByLabel("现实结果说明").fill("手机验证：这次没有完成");
 await page.getByRole("button", {name:"自报未完成",exact:true}).click();
 await page.getByRole("button", {name:"撤回我的结果报告",exact:true}).waitFor();
 await page.locator(".decision").filter({hasText:"小满"}).filter({hasText:"本人自报：未完成"}).waitFor();
 await page.getByLabel("呈现模式", {exact:true}).selectOption("2d");
 await page.locator(".baseline").waitFor({state:"visible"});
 await page.locator(".baseline-card").filter({hasText:"下一次行动"}).filter({hasText:"本人自报：未完成"}).waitFor();
 await page.screenshot({path:path.join(out,"mobile-baseline.png"),fullPage:true});
 const beforeImport = JSON.parse(await page.locator("#json").textContent());
 await page.locator(".import-panel summary").click();
 await page.getByRole("button",{name:"载入合成签到示例",exact:true}).click();
 await page.locator("#checkin-confirm").check();
 await page.getByRole("button",{name:"确认并导入签到",exact:true}).click();
 const importedCard = page.locator(".baseline-card").filter({has:page.locator("strong").getByText("在 合成纸桥工作坊 的签到",{exact:true})});
 await importedCard.waitFor();
 await importedCard.click();
 await page.locator(".provenance summary").click();
 await page.locator(".source-meta").filter({hasText:"2026-09-12T02:00:00Z"}).waitFor();
 const importedState = JSON.parse(await page.locator("#json").textContent());
 const imported = importedState.entities.find(item=>item.source?.record_id==="synthetic-visit-001");
 if(!imported || importedState.basis.through_sequence!==beforeImport.basis.through_sequence+1) throw new Error("Import did not append exactly once");
 await page.getByRole("button",{name:"确认并导入签到",exact:true}).click();
 await page.waitForTimeout(300);
 assert.deepEqual(JSON.parse(await page.locator("#json").textContent()), importedState, "Retry changed state");
 await page.getByLabel("查看身份",{exact:true}).selectOption("bo");
 await importedCard.waitFor({state:"detached"});
 await page.getByLabel("查看身份",{exact:true}).selectOption("alice");
 await importedCard.waitFor();
 await importedCard.click();
 await page.getByLabel("呈现模式",{exact:true}).selectOption("3d");
 await page.locator(".object-label").filter({hasText:"在 合成纸桥工作坊 的签到"}).waitFor();
 await page.getByRole("button",{name:"撤回这段经历",exact:true}).click();
 await page.locator(".object-label").filter({hasText:"在 合成纸桥工作坊 的签到"}).waitFor({state:"detached"});
 await page.getByLabel("呈现模式",{exact:true}).selectOption("2d");
 await importedCard.waitFor({state:"detached"});
 await page.screenshot({path:path.join(out,"mobile-baseline-withdrawn.png"),fullPage:true});
 const overflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth);
 const diag = await page.locator("#diagnostic").textContent();
 fs.writeFileSync(path.join(out,"report.json"), JSON.stringify({errors, overflow, before: JSON.parse(before), after: JSON.parse(diag), finalState, passed: ["correction", "individual accept/decline", "self report", "report withdrawal", "experience withdrawal", "viewer filtering", "reset", "mobile layout", "mobile outcome controls", "orbit input", "3D object labels", "2D state parity", "2D render pause", "2D relations/outcomes", "confirmed checkin import", "idempotent import", "private checkin filter", "withdraw checkin in both views"]}, null, 2));
 await browser.close();
 if(errors.length || overflow) throw new Error(JSON.stringify({errors, overflow}));
 console.log(out);
})().catch(e => { console.error(e); process.exit(1); });
