import test from "node:test";
import assert from "node:assert/strict";
import * as THREE from "three";
import {validatedEntourageIndices,prepareVenueEntourage} from "../src/runtime/VenueEntourage.js";

function fixture(){const geometry=new THREE.BufferGeometry();geometry.setAttribute("position",new THREE.Float32BufferAttribute([0,1,0, .2,1,0, 0,2,0, 10,0,10, 12,0,10, 10,0,12],3));geometry.setIndex([0,1,2,3,4,5]);const meta={schema:"echo-campus.venue-entourage.v1",venueId:"venue-ab-canopy",materialName:"Original default",expectedVertexCount:6,expectedTriangleCount:2,padMeters:.012,triangleIndices:[0],boxes:[{min:[0,1,0],max:[.2,2,0]}]};return {geometry,meta};}
test("Only complete source-person triangle is omitted; ground remains",()=>{const {geometry,meta}=fixture();assert.deepEqual([...validatedEntourageIndices(geometry,meta)],[3,4,5]);assert.deepEqual([...geometry.index.array],[0,1,2,3,4,5]);geometry.dispose();});
test("Reject changed topology or source triangle outside evidence bounds",()=>{const {geometry,meta}=fixture();assert.throws(()=>validatedEntourageIndices(geometry,{...meta,expectedVertexCount:100}),/does not match/);assert.throws(()=>validatedEntourageIndices(geometry,{...meta,triangleIndices:[1]}),/escaped/);geometry.dispose();});
test("Event swaps index; source and disposal restore the exact original geometry",async()=>{const {geometry,meta}=fixture(),material=new THREE.MeshBasicMaterial();material.name=meta.materialName;const mesh=new THREE.Mesh(geometry,material),root=new THREE.Group();root.add(mesh);const handle=await prepareVenueEntourage(root,{venueId:"venue-ab-canopy",fetchImpl:async()=>({ok:true,json:async()=>meta})});assert.equal(handle.diagnostics.removedTriangles,1);assert.equal(mesh.geometry,geometry);handle.setEvent(true);assert.notEqual(mesh.geometry,geometry);assert.equal(mesh.geometry.attributes.position,geometry.attributes.position);assert.equal(mesh.geometry.index.count,3);handle.setEvent(false);assert.equal(mesh.geometry,geometry);handle.setEvent(true);handle.dispose();assert.equal(mesh.geometry,geometry);handle.dispose();geometry.dispose();material.dispose();});
test("Evidence unavailable leaves source intact",async()=>{const root=new THREE.Group(),handle=await prepareVenueEntourage(root,{venueId:"venue-ab-canopy",fetchImpl:async()=>({ok:false,status:404})});assert.match(handle.diagnostics.error,/404/);handle.setEvent(true);assert.equal(handle.diagnostics.applied,false);handle.dispose();});
