const {chromium}=require(process.env.PLAYWRIGHT_MODULE||"playwright");
const fs=require("node:fs"),path=require("node:path"),assert=require("node:assert/strict");
(async()=>{
 const out=process.env.LAB_EVIDENCE_DIR||path.join(require("node:os").tmpdir(),"meetmind-space-evidence");fs.mkdirSync(out,{recursive:true});
 const browser=await chromium.launch({headless:true,...process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{}});
 try{
 const a=await browser.newContext({viewport:{width:1440,height:1100}}),b=await browser.newContext({viewport:{width:390,height:844}});
 const owner=await a.newPage(),guest=await b.newPage(),errors=[];
 for(const page of [owner,guest])page.on("pageerror",e=>errors.push(e.message));
 const base=process.env.LAB_URL||"http://127.0.0.1:4197/";
 await owner.goto(base);await owner.locator("#identity").filter({hasText:"小满"}).waitFor();
 await owner.screenshot({path:path.join(out,"initial-desktop.png"),fullPage:true});
 await owner.locator("#invite").click();await owner.locator("#invite-dialog").waitFor({state:"visible"});const invite=await owner.locator("#invite-link").inputValue();await owner.getByRole("button",{name:"关闭",exact:true}).click();
 await guest.goto(invite);await guest.locator("#join").click();await guest.locator("#identity").filter({hasText:"阿博"}).waitFor();assert.equal(new URL(guest.url()).hash,"");
 const os=await owner.evaluate(()=>JSON.parse(localStorage.getItem("meetmind.shared-space.session.v1")));
 const gs=await guest.evaluate(()=>JSON.parse(localStorage.getItem("meetmind.shared-space.session.v1")));
 assert.equal(os.session_id,gs.session_id);assert.notEqual(os.token,gs.token);
 const initial=await owner.evaluate(()=>window.__space.diagnostics());
 await owner.locator('[data-requirement="work"]').click();
 await owner.waitForFunction(()=>window.__space.state.requirements.find(r=>r.id==="work").enabled);
 await guest.waitForFunction(()=>window.__space.state.requirements.find(r=>r.id==="work").enabled);
 await guest.locator('[data-requirement="exercise"]').click();
 await owner.waitForFunction(()=>window.__space.state.violations.length>0);
 await owner.screenshot({path:path.join(out,"conflict-desktop.png"),fullPage:true});
 await owner.locator('[data-preset="B"]').click();
 await owner.waitForFunction(()=>window.__space.state.violations.length===0&&window.__space.state.objects.find(o=>o.id==="sofa").x===4.65);
 await guest.waitForFunction(()=>window.__space.state.violations.length===0);
 const current=await owner.evaluate(()=>window.__space.diagnostics());
 assert.deepEqual(initial.object_uuids,current.object_uuids);assert.deepEqual(initial.mesh_uuids,current.mesh_uuids);
 await owner.locator('[data-tab="decide"]').click();await guest.locator('[data-tab="decide"]').click();
 await owner.getByRole("button",{name:"我接受这个版本",exact:true}).click();
 await guest.waitForFunction(()=>window.__space.state.decisions.alice?.status==="accepted");
 await guest.getByRole("button",{name:"我接受这个版本",exact:true}).click();
 await owner.waitForFunction(()=>window.__space.state.decisions.bo?.status==="accepted");
 await owner.locator("#x").fill("1.2");await owner.getByRole("button",{name:"更新位置",exact:true}).click();
 await owner.waitForFunction(()=>window.__space.state.decisions.alice.revision<window.__space.state.revision);
 await guest.locator(".decision").filter({hasText:"旧方案"}).first().waitFor();
 await owner.locator("#mode2d").click();assert.equal(await owner.evaluate(()=>window.__space.diagnostics().mode),"2d");
 await owner.screenshot({path:path.join(out,"plan-desktop.png"),fullPage:true});
 await owner.locator('[data-tab="story"]').click();await owner.getByLabel("纠正office",{exact:true}).fill("以后每周只有一天在家办公，工作区要求需要重新讨论。");
 await owner.locator('form[data-memory="office"]').getByRole("button",{name:"保存这段变化",exact:true}).click();
 await owner.waitForFunction(()=>window.__space.state.requirements.find(r=>r.id==="work").review_needed);
 await owner.locator('[data-tab="needs"]').click();await owner.locator('[data-requirement="work"]').click();
 await owner.waitForFunction(()=>!window.__space.state.requirements.find(r=>r.id==="work").review_needed);
 await owner.locator('[data-tab="decide"]').click();
 await owner.getByLabel("我的下一步",{exact:true}).fill("周末量一下门宽，确认家具尺寸。");await owner.getByRole("button",{name:"留下我的行动",exact:true}).click();
 await owner.getByRole("button",{name:"自报完成",exact:true}).click();
 await guest.waitForFunction(()=>window.__space.state.actions.some(a=>a.status==="done"));
 const download=owner.waitForEvent("download");await owner.locator("#export").click();const file=await download;await file.saveAs(path.join(out,"summary.md"));assert.match(fs.readFileSync(path.join(out,"summary.md"),"utf8"),/本人自报/);
 await guest.reload();await guest.locator("#identity").filter({hasText:"阿博"}).waitFor();
 assert.ok(await guest.evaluate(()=>window.__space.state.actions.some(a=>a.status==="done")));
 assert.equal(await guest.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await guest.screenshot({path:path.join(out,"mobile.png"),fullPage:true});
 const sequence=await guest.evaluate(()=>window.__space.state.sequence);
 const forged=await b.request.post(base+"space-api/command",{headers:{Authorization:"Bearer "+gs.token},data:{expected_sequence:sequence,request_id:"forged-owner-req",command:{type:"requirement.set",requirement_id:"work",enabled:false}}});assert.equal(forged.status(),400);
 assert.deepEqual(errors,[]);
 fs.writeFileSync(path.join(out,"report.json"),JSON.stringify({passed:["two identities","own requirements","geometry conflict","preset resolution","mesh identity","version-bound decisions","2D mode","memory correction review","own action and report","download","reload","mobile no overflow","owner boundary"],errors,diagnostics:current},null,2));
 console.log(out);
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
